### ISSUE TITLE
Say, do you play L e a g u e o f L e g e n d s ? 

### ISSUE THREAD

**Issue by JupiterSayuri451** [Swipefly/INHERENTLY_BROKEN#22]

**Comment by Quintavia** [comment]
This quote was recorded by a disciple, not written by the Salty One himself; the quivering young follower was invoking the booming voice of the Salty One by spacing the letters. A lazy technique for sure, but you can’t blame the poor fellow; his eardrums had burst and he was trying his best. It’s best for the reader, in order to fully appreciate the magnitude of the Salty One, to picture him standing above you and bellowing at you, prostrate at his feet. You should feel honored.
