### ISSUE TITLE
unfortunately the 90s was at least 700 years ago so

### ISSUE THREAD

**Issue by JupiterSayuri451** [Swipefly/INHERENTLY_BROKEN#26]

**Comment by Swipefly** [comment]
Our Salty One emphasizes that time does not matter. Time is merely a way of comprehending an order of events for our feeble human minds. Memories are what is important, not the present. We must plan for the future, remember the past, and ignore the present. The present is merely a time for thinking about the past or future, nothing more, nothing less. Our brains can only think about the future or past since the present has already slipped by.
