### ISSUE TITLE
Well, I used to play, but then I took an Imbalanced Gameplay to the knee.

### ISSUE THREAD

**Issue by JupiterSayuri451** [Swipefly/INHERENTLY_BROKEN#6]

**Comment by Swipefly** [comment]
The Salty One does not joke or play. He is laser focused on accepting Salt and rage into his heart. Humor is not within his comprehension because he wishes it to be so. One cannot have both anger and humor in one's heart without demeaning one virtue or the other. Salt is most important, so other emotions must be squashed.
